var sides = [
  "Miso Glazed Carrots",
  "Coleslaw",
  "Potato Salad",
  "Scalloped Potatoes",
  "Sweet Potato Tots",
  "Dirty Rice",
  "Caeser Salad",
  "Gyoza",
  "Garlic Butter Green Beans",
  "Hush Puppies",
];

var mains = [
  "Spaghetti Casserole",
  "Pineapple Chicken",
  "Dressing",
  "Mango Stir Fry",
  "Link",
  "Chicken Parmesean",
  "Cajun Gumbo",
  "BBQ Chicken Burgers",
  "Pho",
  "Quesadilla",
  "Chicken Fried Steak",
  "Sheet Pan Fajitas",
  "Margarita Pizza",
];

var desserts = [
  "Apple Pie",
  "Lemon Apple Pie",
  "Pound Cake",
  "Banana Bread",
  "SnickerDoodle Cookie",
  "Cheesecake",
  "Birthday Cake",
  "Baklava",
  "Ambrosia",
  "Truffle Butter",
  "Tres Leches",
  "Bread Pudding",
  "Cookie Brownie",
  "Apple Pie",
  "Sweet Potato Pie",
  "Cupcakes",
  "Strawberry Cake",
];
